### ISSUE TITLE
WIP Fix linting warnings

### ISSUE THREAD

**Issue by BBosman** [aurelia/aurelia#249]
# 💬 RFC

I started pocking around the codebase of vNext today and noticed that running `npm run lint` gives a huge amount of linting warnings. Do these need fixing? If so, I can start making PR's for them. Added benefit for me is that I get to learn the codebase a bit while doing it.

## 🔦 Context

I thought I'd ask the question here first, before I started doing the work and it turns out that it's not (yet) needed/wanted. And also to get some feedback on how to approach this, if it is wanted.

My idea would be to create a PR per rule to keep the PR's easier to review and less prone to merge conflicts, or is a split along package (for Changelog purposes) also wanted? 

## 💻 Progress

- [X] Many linting fixes (#251, #252, #253, #255, #256, #257, #262, #274, #277, #290)
- [X] Use official Reflect metadata API type definitions (#261)
- [X] Disable promise-function-async linting rule (#280)
- [X] Remove StrictAny in favour of unknown (#294)
- [X] Turn off `no-reserved-keywords` rule. (#297)
- [X] Rename `fromIndex`, `toIndex` and `messageType` back to `from`, `to` and `type`. Partially reverts #290. (#301)
- [X] Fix `no-floating-promises` violations. (#304)
- [X] Fix `no-shadowed-variable` violations. (#338)
- [X] Fix `no-unnecessary-type-assertion` violations (in `expression-parser.ts`) (#337)
- [X] Fix `no-any` violations in `di.ts` (#338)
- [ ] ~~Fix other `no-any` violations~~
- [ ] Set `completed-docs` to `warning` and all other linting violations to `error` (#418)

**Comment by EisenbergEffect** [comment]
I do think this would be helpful but we'll want to synchronize where you are making those changes so it doesn't create conflicts with other work. I'm thinking that you could look through the code in the `kernel` package and make some improvements there. @fkleuver You do you expect you'll be in there? Or are you mostly in runtime right now?

**Comment by fkleuver** [comment]
> Do these need fixing?

Yep, eventually we would like everything to be linting error-free.

It's probably safest (in terms of not risking wasted effort and/or merge conflicts) to start in the more stable areas. That would be `packages/kernel`, `packages/jit`, and `packages/runtime/binding`. I have some refactorings planned for the observers but those will not affect the typings.

`packages/runtime` (top-level) and `packages/runtime/templating` is currently undergoing a huge refactor so better not spend too much time there right now :)

> My idea would be to create a PR per rule to keep the PR's easier to review and less prone to merge conflicts

Per rule or per file or per group of related classes, anything that makes sense is fine. Keeping it relatively small is probably a good idea for starters

> or is a split along package (for Changelog purposes) also wanted?

Nah, linting fixes by their semver category ("chore" or "style" I believe) don't end up in changelogs.

Thanks for offering your help :)
Looking forward to the PR!

**Comment by fkleuver** [comment]
(I'll submit my WIP PR in a few minutes so you'll know what to avoid)

**Comment by fkleuver** [comment]
@BBosman I just noticed that one of your previous PR's actually broke the build. The runtime doesn't seem to like the `unknown`s everywhere. This is also my fault because I should have pulled and built before approving the changes - I assumed you did. I suppose you couldn't have known that was necessary though.
In any cases, the result feels dramatic but the cause is actually a small and simple one to fix: just don't return `unknown` from a synthetic constructor signature (this breaks decorators). I think returning `any` and disabling the tslint rule for that one line is a fair thing to do.

**Comment by fkleuver** [comment]
@BBosman @EisenbergEffect I really like the results of this effort so far and would like to propose that we commit to getting rid of all linting warnings.
Then we can eventually let linting warnings be errors. CI already runs a lint job, so that job will cause the CI check to fail whenever any commit introduces new linting errors.
@BBosman let's take the question mark out of the title and @EisenbergEffect let's make this a milestone? :)

**Comment by EisenbergEffect** [comment]
I agree! @BBosman since you've got the best sense of where we're at on this. Any notion of how much work there is left to fix the lint errors up completely? I can create a milestone, but I want it to be realistically timed in the scheme of things 😏

**Comment by fkleuver** [comment]
I'll let @BBosman comment on the amount of work left. As for milestone, I think we want to try and place this either on 0.4.0 or 0.5.0, so the linting can be brutally enforced when router and plugins start taking off. It'll be much less work to get those linting-proof during migration/creation than after the fact, I'm guessing

**Comment by fkleuver** [comment]
Yep, that's my thinking as well.

**Comment by BBosman** [comment]
Once #274 is merged and we don't count `completed-docs` and `no any` we have about 20-ish violations left. About half of those are Promise-related. I can pick of a few of those left, but most of those require a bit more intimate knowledge of the codebase than I currently have.

Looking at `no-any` there's +/- 150 left, although that's a bit of a red herring as we should take the `StrictAny` usage in account as well, as we want to migrate most of those to `unknown`. Giving a timeframe for that is difficult as I'm still figuring out what large parts of the codebase are actually doing 😊.

I didn't bother counting the `completed-docs` violations, because it **a lot**. And although documentation is crucial, with the amount of flux and refactoring that the codebase is going through my suggestion would be to document what's needed now and do the rest once the codebase settled a bit.

So my advice for now would be to fix those 20-ish violations and the set the default level to `error`, but make an exception for `no-any` and `completed-docs` and keep those explicitly on `warning` for now.

**Comment by fkleuver** [comment]
> So my advice for now would be to fix those 20-ish violations and the set the default level to error, but make an exception for no-any and completed-docs and keep those explicitly on warning for now.

Sounds like a solid plan for `completed-docs`, that's a very hard one to fix anytime soon and doesn't really relate to typing anyway. I think `no-any` might not be needed, but I can/should probably help with that on the observer/ast/di side. Can be very quick to do when knowing the internals and various constraints.

**Comment by BBosman** [comment]
Updated the issue description with a checklist of work done and work that still needs to be done (as far as I can tell) to mark this issue as Done.

Additions welcome. 😄

**Comment by fkleuver** [comment]
Excellent. Looks good so far, if anything comes up I'll be sure to raise it :)

**Comment by EisenbergEffect** [comment]
@BBosman Are we able to close this one now?

**Comment by BBosman** [comment]
@EisenbergEffect Almost. 

#418 is the missing piece. We tried in #366, but we had to revert. The problem is that CircleCI flags `tslint` violations which don't trigger locally. No problem as long as they're warnings, but if we set them to error...

@fkleuver and I need to figure out what the difference between those environments is to fix this and then we can hopefully resolve this issue.

**Comment by fkleuver** [comment]
@BBosman I haven't been able to look into that yet, but I did notice that there are some duplicate rules between different rule sets. Useless cast + unnecessary type assertion is one such pair, I believe. Is there any way we can eliminate that? I have this gut feeling it might be related
